create table if not exists public.agendamentos (
  id bigint generated by default as identity primary key,
  nome text not null,
  servico text not null,
  data date not null,
  horario time not null,
  created_at timestamptz not null default now(),
  constraint agendamentos_data_horario_unique unique (data, horario)
);

alter table public.agendamentos enable row level security;

drop policy if exists "Agendamentos podem ser consultados" on public.agendamentos;
create policy "Agendamentos podem ser consultados"
on public.agendamentos
for select
to anon
using (true);

drop policy if exists "Agendamentos podem ser criados" on public.agendamentos;
create policy "Agendamentos podem ser criados"
on public.agendamentos
for insert
to anon
with check (true);

grant select, insert on public.agendamentos to anon;
grant usage, select on sequence public.agendamentos_id_seq to anon;
